clear all
data = load('ex4data.mat');

data8 = data.data8;
data16 = data.data16;
data32 = data.data32;
data64 = data.data64;
data128 = data.data128;
data256 = data.data256;
data512 = data.data512;

burnedTrees8 = data8(:,1);
burnedTrees16 = data16(:,1);
burnedTrees32 = data32(:,1);
burnedTrees64 = data64(:,1);
burnedTrees128 = data128(:,1);
burnedTrees256 = data256(:,1);
burnedTrees512 = data512(:,1);
tweak = 0;
figure(1)
tau8 = PlotLinFit(burnedTrees8, 8, tweak, 'b-');
hold on
tau16 = PlotLinFit(burnedTrees16, 16, tweak, 'b-');
hold on
tau32 = PlotLinFit(burnedTrees32, 32, tweak, 'b-');
hold on
tau64 = PlotLinFit(burnedTrees64, 64, tweak, 'b-');
hold on
tau128 = PlotLinFit(burnedTrees128, 128, tweak, 'b-');
hold on
tau256 = PlotLinFit(burnedTrees256, 256, tweak, 'b-');
hold on
tau512 = PlotLinFit(burnedTrees512, 512, tweak, 'b-');
hold off

% yAxis = [tau8, tau16, tau32, tau64, tau128, tau256 ];
% xAxis = [(1/8), (1/16), (1/32), (1/64), (1/128), (1/256)];

yAxis = [tau8, tau16, tau32, tau64, tau128, tau256, tau512 ];
xAxis = [(1/8), (1/16), (1/32), (1/64), (1/128),(1/256), (1/512)] ;

figure(2)
plot(xAxis, yAxis, 'r');
xlabel('1/N');
ylabel('\tau')
title(['\tau as function of 1/N. Data points generated by excluding ' num2str(tweak*100) '% of the data. Lines between data points.']);
hold on
for p = 1:7
    plot(xAxis(p), yAxis(p), 'ro')
    hold on
end
hold off

figure(3)
[p, ignore] = polyfit(xAxis(4:7), yAxis(4:7), 2);
pX = (0:0.001:(1/64));
pY = polyval(p, pX);
plot(pX, pY, 'g')
hold on
for p = 1:7
    plot(xAxis(p), yAxis(p), 'go')
    hold on
end

xlabel('1/N');
ylabel('\tau')
title([ '\tau as function of 1/N, with a polynomial fit. Each data point generated by excluding ' num2str(tweak*100) '% of the data (larger RFS)'])
hold off
